# Generated by Django 3.2.5 on 2021-07-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
