# Generated by Django 3.2.5 on 2021-07-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('mobile', 'mobile'), ('laptop', 'laptop'), ('shirt', 'shirt'), ('jeans', 'jeans')], max_length=20),
        ),
    ]
