# Generated by Django 3.2.5 on 2021-07-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210725_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Panding', 'Panding'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Cancelled', 'Cancelled'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
