# Generated by Django 3.2.5 on 2021-07-30 13:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='productImage'),
        ),
    ]
